// Modular Vanilla JS: Full Logic, No Frameworks
emailjs.init('CHqNrS_37-ZHjibQR');
const firebaseConfig = {apiKey: "AIzaSyDC22Z2fuGTc7j9Gm7JKO5dB2NJTiHGIB0", authDomain: "ridesafe-app-2faa9.firebaseapp.com", databaseURL: "https://ridesafe-app-2faa9-default-rtdb.firebaseio.com/", projectId: "ridesafe-app-2faa9", storageBucket: "ridesafe-app-2faa9.appspot.com", messagingSenderId: "516451873273", appId: "1:516451873273:web:0bd8e6027b72c1e0580d28"};
firebase.initializeApp(firebaseConfig);
const db = firebase.database();
const countryClub = {lat: 30.4103, lng: -91.1868};
let pickup = '', dropoff = '', date = new Date().toISOString().split('T')[0], time = '09:00', distance = {miles: 0, durationSecs: 0}, price = {price: 0, pickupTime: ''}, bookings = {}, currentWeekStart = new Date(Date.now() - (new Date().getDay() - 1) * 86400000), loading = false, map, directionsRenderer;
function timeToMins(timeStr) { const [h, m] = timeStr.split(':').map(Number); return h * 60 + m; }
function formatTime12(timeStr) { const [h, m] = timeStr.split(':').map(Number); const ampm = h >= 12 ? 'PM' : 'AM'; h = h % 12 || 12; return `${h}:${m.toString().padStart(2, '0')} ${ampm}`; }
async function getDistance(origin, dest) { const response = await fetch(`https://maps.googleapis.com/maps/api/distancematrix/json?origins=${encodeURIComponent(origin)}&destinations=${encodeURIComponent(dest)}&key=AIzaSyDCtBJCtWAp1vUMEWfj9qX-gb1IMqiln6w`); if (!response.ok) throw new Error('API error'); const data = await response.json(); if (data.status !== 'OK' || data.rows[0].elements[0].status !== 'OK') throw new Error(data.error_message || 'Invalid locations'); return data.rows[0].elements[0]; }
async function calcDistance(origin, dest) { if (!origin || !dest) return {miles: 0, durationSecs: 0}; try { const {distance, duration} = await getDistance(origin, dest); const miles = Math.round(distance.value / 1609.34); const durationSecs = duration.value; console.log('Distance:', {miles, durationSecs}); return {miles, durationSecs}; } catch (err) { console.error('Distance calc failed:', err); return {miles: 0, durationSecs: 0}; } }
function getSurge(dateStr, timeStr, pickupTimeStr) { const dt = new Date(`${dateStr}T${timeStr}:00`); const pickupDt = new Date(`${dateStr}T${pickupTimeStr}:00`); const hour = dt.getHours() + dt.getMinutes() / 60; const pickupHour = pickupDt.getHours() + pickupDt.getMinutes() / 60; const day = dt.getDay(); let surge = 1; if (hour >= 16.5 && hour <= 18.5 && day >= 1 && day <= 5) surge = 1.4; if (day === 5 && hour >= 17) surge = 1.6; if ((day === 0 || day === 6) && hour >= 20) surge = 1.8; if (pickupHour >= 3 && pickupHour < 7) surge *= 1.15; if (pickupHour >= 22 || pickupHour < 3) surge *= 1.3; return surge; }
function calcPrice(miles, durationSecs, date, time) { if (!miles || !date || !time || miles === 0) return {price: 0, pickupTime: ''}; try { const arrivalDt = new Date(`${date}T${time}:00`); const pickupDt = new Date(arrivalDt.getTime() - (durationSecs * 1000 + 300000)); const pickupTimeStr = pickupDt.toTimeString().split(' ')[0].substring(0, 5); const surge = getSurge(date, time, pickupTimeStr); const price = miles * surge; const roundedPrice = Math.round(price * 100) / 100; console.log('Price:', {miles, surge, price: roundedPrice, pickupTime: pickupTimeStr}); return {price: roundedPrice, pickupTime: pickupTimeStr}; } catch (err) { console.error('Price calc failed:', err); return {price: 0, pickupTime: ''}; } }
function prevWeek() { currentWeekStart.setDate(currentWeekStart.getDate() - 7); renderWeekPicker(); }
function nextWeek() { currentWeekStart.setDate(currentWeekStart.getDate() + 7); renderWeekPicker(); }
function renderWeekPicker() { const days = []; for (let i = 0; i < 7; i++) { const day = new Date(currentWeekStart); day.setDate(day.getDate() + i); days.push(day); } let html = ''; days.forEach((day, idx) => { const dayStr = day.toISOString().split('T')[0]; const isSelected = date === dayStr; const dayOfWeek = day.getDay(); const dayBookings = bookings[dayStr] || []; const bookedHours = dayBookings.reduce((total, b) => total + (b.durationMins || 60) / 60, 0); let dayClass = 'green'; if (dayOfWeek === 0) dayClass = 'sunday'; else if (bookedHours > 4) dayClass = 'red'; else if (bookedHours > 2 || dayOfWeek >= 4) dayClass = 'orange'; const hasSurge = dayOfWeek >= 4 && dayOfWeek <= 6; const tripCount = dayBookings.length; const showTrips = dayClass !== 'green' && dayClass !== 'sunday' && tripCount > 0; const surgeLabel = hasSurge ? '<span class="surge-label">Surge Pricing</span>' : '<span class="surge-placeholder"></span>'; const dayText = day.toLocaleDateString('en-US', {weekday: 'short', month: 'short', day: 'numeric'}); const tripsHtml = showTrips ? `<span class="trips-label" style="color: ${dayClass};">${tripCount} Trips</span>` : ''; html += `<div class="day-wrapper">${surgeLabel}<div class="day-button ${isSelected ? 'selected' : ''} ${dayClass}" onclick="${dayClass !== 'sunday' ? `setDate('${dayStr}')` : ''}">${dayText}${tripsHtml}</div></div>`; }); document.querySelector('.week-days').innerHTML = html; }
function renderTimePicker() { const times = []; for (let h = 6; h <= 22; h++) { times.push(`${h.toString().padStart(2, '0')}:00`); if (h < 22) times.push(`${h.toString().padStart(2, '0')}:30`); } let html = ''; times.forEach(t => { const durMins = distance.durationSecs / 60; const dayBookings = bookings[date] || []; const booked = dayBookings.some(b => { const bPickup = timeToMins(b.pickupTime); const bEnd = bPickup + (b.durationMins || 60); const arrivalMins = timeToMins(t); const pickupMins = arrivalMins - durMins; return Math.max(pickupMins, bPickup) < Math.min(arrivalMins, bEnd); }); const display = formatTime12(t); const selected = t === time ? 'selected' : ''; const bookedClass = booked ? 'booked' : ''; html += `<div class="time-option ${selected} ${bookedClass}" onclick="${booked ? '' : `setTime('${t}')`}">${display}${booked ? ' (Booked)' : ''}</div>`; }); document.getElementById('time-picker').innerHTML = html; }
function setPickup(val) { pickup = val; updateDistance(); }
function setDropoff(val) { dropoff = val; updateDistance(); }
function setDate(val) { date = val; renderWeekPicker(); renderTimePicker(); updatePrice(); }
function setTime(val) { time = val; renderTimePicker(); updatePrice(); }
async function updateDistance() { distance = await calcDistance(pickup, dropoff); updatePrice(); renderTimePicker(); updateMap(); toggleBookBtn(); }
function updatePrice() { price = calcPrice(distance.miles, distance.durationSecs, date, time); const estEl = document.getElementById('estimate'); if (price.price > 0) { estEl.innerHTML = `<p>Estimated: $${price.price} (${distance.miles} miles | Pickup ~${formatTime12(price.pickupTime)})</p>`; estEl.style.display = 'block'; } else { estEl.style.display = 'none'; } toggleBookBtn(); }
function toggleBookBtn() { const btn = document.getElementById('book-btn'); btn.disabled = loading || !pickup || !dropoff || !date || !time || price.price === 0; }
function updateMap() { if (!map || !pickup || !dropoff) return; const geocoder = new google.maps.Geocoder(); Promise.all([geocoder.geocode({address: pickup}), geocoder.geocode({address: dropoff})]).then(([pResults, dResults]) => { if (pResults[0] && dResults[0]) { const request = {origin: pResults[0].geometry.location, destination: dResults[0].geometry.location, travelMode: 'DRIVING'}; new google.maps.DirectionsService().route(request, (result, status) => { if (status === 'OK') { if (directionsRenderer) directionsRenderer.setMap(null); directionsRenderer = new google.maps.DirectionsRenderer({map, directions: result}); } }); } }).catch(console.error); }
async function handleBook() { if (!pickup || !dropoff || !date || !time || price.price === 0) return; loading = true; toggleBookBtn(); try { const durationMins = Math.round(distance.durationSecs / 60); const booking = {pickup, dropoff, date, arrivalTime: time, pickupTime: price.pickupTime, miles: distance.miles, price: price.price, durationMins, timestamp: Date.now()}; const newKey = db.ref('bookings').push().key; await db.ref(`bookings/${date}/${newKey}`).set(booking); const templateParams = {pickup, dropoff, date, arrival_time: time, pickup_time: price.pickupTime, miles: distance.miles, price: `$${price.price}`, to_email: 'lancewoolie@gmail.com'}; // Updated driver email await emailjs.send('service_2ss0i0l', 'template_k8h7f8m', templateParams); // Updated template ID alert('Booking confirmed! Email sent to driver.'); pickup = dropoff = time = '09:00'; document.getElementById('pickup').value = document.getElementById('dropoff').value = ''; updateDistance(); } catch (err) { console.error('Booking failed:', err); alert('Booking failed—check console.'); } loading = false; toggleBookBtn(); }
function initRideSafe() { map = new google.maps.Map(document.getElementById('map'), {zoom: 10, center: countryClub}); directionsRenderer = new google.maps.DirectionsRenderer({map}); const pickupInput = document.getElementById('pickup'); const dropoffInput = document.getElementById('dropoff'); const autocompletePickup = new google.maps.places.Autocomplete(pickupInput, {types: ['address']}); autocompletePickup.addListener('place_changed', () => setPickup(autocompletePickup.getPlace().formatted_address)); const autocompleteDropoff = new google.maps.places.Autocomplete(dropoffInput, {types: ['address']}); autocompleteDropoff.addListener('place_changed', () => setDropoff(autocompleteDropoff.getPlace().formatted_address)); pickupInput.addEventListener('input', (e) => { if (!autocompletePickup.getPlace()) setPickup(e.target.value); }); dropoffInput.addEventListener('input', (e) => { if (!autocompleteDropoff.getPlace()) setDropoff(e.target.value); }); db.ref('bookings').on('value', (snapshot) => { bookings = snapshot.val() || {}; Object.keys(bookings).forEach(d => bookings[d] = Object.values(bookings[d])); renderWeekPicker(); renderTimePicker(); }); renderWeekPicker(); renderTimePicker(); updateDistance(); }
window.initRideSafe = initRideSafe; // Global callback for Google Maps
